- name: create directory for java 
  file: path={{ java_distr_path }} state=directory mode=0775
  
- name: just in case install wget hehehe
  yum: name=wget state=latest

- name: download java jdk
  shell: "wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
'http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm' -P {{ java_distr_path }}"

- name: install java jdk
  yum: name={{ java_distr_path }}/jdk-8u131-linux-x64.rpm state=present

- name: create link to java 
  file: state=link src={{ java_installed_path }} dest={{ java_path }}
